repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.0
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format

- repo: local
  hooks:
  - id: bandit
    name: Bandit
    files: '.+\.py'
    exclude: 'tests/.*'
    entry: bandit
    language: python
  - id: python-safety-dependencies-check
    entry: safety
    name: Safety
    args: [check, -r, requirements.txt, --full-report]
    language: system
    pass_filenames: false
